unix {
    interactive
    log /var/log/vpp.log
    full-coredump
    cli-listen /run/vpp/cli.sock
    cli-no-pager
    gid 0
    poll-sleep-usec 100
}

api-trace {
    on
}

buffers {
    page-size default
}

statseg {
    size 32M
    page-size 4k
    per-node-counters on
}

plugins {
    plugin default { enable }
    plugin dpdk_plugin.so { disable }
    plugin perfmon_plugin.so { disable }
    plugin subscriber_dp_plugin.so { enable }
}

